# Configuración de ejemplo del servidor WireGuard (sandbox / demo)
[Interface]
Address = 10.9.0.1/24
ListenPort = 51820
PrivateKey = QFXmABCDEFsandboxServerPrivateKeyNoRealdGVzdA0=
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT

# ana-portatil
[Peer]
PublicKey = AnaPubKeyZZZsandboxNoRealZZZZZZZZZZZZZZ012345=
AllowedIPs = 10.9.0.2/32

# luis-movil
[Peer]
PublicKey = LuisPubKeyZZsandboxNoRealZZZZZZZZZZZZZ678901=
AllowedIPs = 10.9.0.3/32

# tablet-almacen
[Peer]
PublicKey = TabletPubKeysandboxNoRealZZZZZZZZZZZZ234567=
AllowedIPs = 10.9.0.4/32
